server:
  port: 8083
spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: search-service
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册


  elasticsearch:
    rest:
      uris: localhost:9200


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
logging:
  level:
    com.skt.search.client.GoodsClient: debug