server:
  port: 10010
spring:
  application:
    name: skt-gateway
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    item-service: /item/**
    search-service: /search/**
  ignored-patterns: /upload/** #忽略的路径,不路由
  ignored-services:
    - upload-service #忽略这个服务